# Generated by Django 3.2.22 on 2023-10-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='party',
            new_name='number_of_persons',
        ),
    ]
