# Generated by Django 3.2.22 on 2023-10-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_menu_antipasti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('Antipasti', 'Antipasti'), ('APrimo', 'APrimo'), ('IlSecondo', 'IlSecondo'), ('IlDolce', 'IlDolce'), ('Bevande', 'Bevande')], max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Antipasti',
        ),
    ]
